CREATE TABLE [dbo].[Users] (
    [UserID]             INT            IDENTITY (1, 1) NOT NULL,
    [Username]           NVARCHAR (16)  NOT NULL,
    [Password]           NVARCHAR (16)  NOT NULL,
    [Email]              NVARCHAR (64)  NOT NULL,
    [HomePage]           NVARCHAR (256) NULL,
    [Avatar]             NVARCHAR (256) NULL,
    [MSN]                NVARCHAR (64)  NULL,
    [AIM]                NVARCHAR (64)  NULL,
    [Yahoo]              NVARCHAR (64)  NULL,
    [ICQ]                NVARCHAR (64)  NULL,
    [LoggedIn]           BIT            CONSTRAINT [DF_Users_LoggedIn] DEFAULT ((0)) NOT NULL,
    [SessionID]          BIGINT         CONSTRAINT [DF_Users_SessionID] DEFAULT ((0)) NOT NULL,
    [Location]           NVARCHAR (64)  NULL,
    [Interests]          NVARCHAR (128) NULL,
    [HideContactInfo]    BIT            CONSTRAINT [DF_Users_HideContactInfo] DEFAULT ((0)) NOT NULL,
    [AccessLevel]        INT            CONSTRAINT [DF_Users_AccessLevel] DEFAULT ((0)) NOT NULL,
    [ActivationCode]     BIGINT         CONSTRAINT [DF_Users_ActivationCode] DEFAULT ((0)) NOT NULL,
    [Activated]          BIT            CONSTRAINT [DF_Users_Activated] DEFAULT ((1)) NOT NULL,
    [ActivationAttempts] TINYINT        CONSTRAINT [DF_Users_ActivationAttempts] DEFAULT ((0)) NOT NULL,
    [Suspended]          BIT            CONSTRAINT [DF_Users_Suspended] DEFAULT ((0)) NOT NULL,
    [Dead]               BIT            CONSTRAINT [DF_Users_Dead] DEFAULT ((0)) NOT NULL,
    [DieDate]            DATETIME       CONSTRAINT [DF_Users_DieDate] DEFAULT (getdate()) NOT NULL,
    [SignUpDate]         DATETIME       CONSTRAINT [DF_Users_SignUpDate] DEFAULT (getdate()) NOT NULL,
    [MessagesSent]       TINYINT        CONSTRAINT [DF_Users_MessagesSent] DEFAULT ((0)) NOT NULL,
    [Threads]            INT            CONSTRAINT [DF_Users_Threads] DEFAULT ((0)) NOT NULL,
    [Posts]              INT            CONSTRAINT [DF_Users_Posts] DEFAULT ((0)) NOT NULL,
    [ShipSpeed]          FLOAT (53)     CONSTRAINT [DF_Users_ShipSpeed] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserID] ASC)
);

